### ISSUE TITLE
'Cannot get annotation information' - Error

### ISSUE THREAD

**Issue by dpma** [guoc/excerptor#1]
Hi,

I have used excerptor before when I tried it to make sure that I had installed it correctly, and it worked fine. Now however I am seeing the error message mentioned above. Could you help me out?

Thank you!

**Comment by guoc** [comment]
What did you do during this period? System update? What's current system version?
Which app do you use? Skim or Preview?

**Comment by dpma** [comment]
I am using Skim, and using version 10.11. I don't think I updated the version afterwards, at least I know I did the installation procedure as described here https://github.com/guoc/excerptor/wiki/SIMBL-Installation-for-OS-X-10.11

**Comment by guoc** [comment]
Is the PDF file is copiable?

**Comment by dpma** [comment]
Yes, I can copy text from the pdf file.

**Comment by guoc** [comment]
Have you tried other PDF files? or restart your computer? Now I have no clue to fix it.
When did you install Excerptor? 10.10 or 10.11?

**Comment by dpma** [comment]
Other PDF files behave similarly. I will try to restart the computer, reinstall SIMBL and excerptor. If successful, I will update the thread. Thank you anyway!

**Comment by guoc** [comment]
The issue may be caused by System Integrity Protection (SIP) introduced in 10.11
If you installed Excerptor on 10.10, please check https://github.com/guoc/excerptor#update-os-x

**Comment by Monopa** [comment]
I'm having the same issue. Installed it, including SIMBL, on 10.11.

**Comment by guoc** [comment]
I am rewriting the code with Swift 2.1, and I will test it on a brand new OS X. Hope I can complete these things in one week.

**Comment by guoc** [comment]
I just updated Excerptor and wiki.
Have you done the steps in https://github.com/guoc/excerptor/wiki/SIMBL-Installation-for-OS-X-10.11 ?
This is required for OS X 10.11
