### ISSUE TITLE
Problems in macOS Sierra

### ISSUE THREAD

**Issue by mnvwvnm** [guoc/excerptor#4]
I tried to use this great tool for the first time but after all the installation steps it didn't work!
I thought that I had made something wrong... But then I noticed that apps like _Skim_ or _Preview_ missing the contextual "Services" menu!
Considering the recent problems with the PDFKit on macOS sierra, is this the reason for the missing contextual Services menu on the pdf files and the Excerptor fail?
I select some text in pdf file, right-click and no "services" item available. 

Anu ideia?

**Comment by guoc** [comment]
I'm still in OS X 10.11. I'll test Excerptor on macOS Sierra when I get a chance and try to fix it.
In your case, it seems the OS didn't recognize the services. Normally restarting OS may helps if there aren't new bugs introduced in macOS Sierra.

**Comment by mnvwvnm** [comment]
Thanks for your answer. Restart OS not helps. 
Services works with others file formats. The problem persists in pdf files (in Preview, Skim, Devonthink...).
For example, in your animated gif (https://raw.githubusercontent.com/guoc/excerptor/master/screenshots/excerpt_to_pasteboard.gif) when right-click we found the item "services" with multiple options. As example, if I open a pdf file on Preview, after the right-click the Services item not appears!
The Excerptor installation doesn't create this kind of problem, right?

**Comment by guoc** [comment]
macOS Sierra 10.12 introduced this issue #8.
Actually, any text services are not available in Preview or Skim in macOS Sierra.
