### ISSUE TITLE
Select PDF contents failed

### ISSUE THREAD

**Issue by sixshotx** [guoc/excerptor#5]
Hi, I am testing the Excerptor 1.1.1 in Preview on 10.11.6, following the gif example. The excerptor throws the error "Could not get selection/animation information", and system also reports "The “Excerptor: Excerpt Selection To Pasteboard” service could not be used because the application did not respond to a request for services.". Please help. Thanks.

**Comment by forsil** [comment]
I have the same behaviour with Preview in 10.11.6.

**Comment by guoc** [comment]
@sixshotx @forsil 
Hi, I just released a new [version](https://github.com/guoc/excerptor/releases/tag/v1.2). It fixed some bugs and also can give useful messages if errors happen.
Reopen the issue if necessary.
