### ISSUE TITLE
Devonthink support?

### ISSUE THREAD

**Issue by rxng** [guoc/excerptor#7]
Hi,

Saw that devonthink was supported, but when I try to highlight within devonthink itself, the service doesn't pop up?

Thanks

**Comment by guoc** [comment]
Sorry for late reply.
The DEVONthink Pro support is that, for PDF files stored in DEVONthink Pro, Excerptor locates them by their UUID given by DEVONthink. So wherever a PDF file moves, as long as it is in DEVONthink, Excerptor can always find it.
